### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by nadar** [unglue-workflow/server#1]
i would recommend to release strictly according to semver.

+ 1.x.x major release contains breaks in the current api (lets say renaming an endpoint, renaming an option flag, rename the response array.. stuff like this)
+ x.1.x minor release contains new features in the api
+ x.x.1 patch release contains, surprise, patches and hot fixes.

Our goal should also be to keep major releases as low as possible.

**Comment by TheMaaarc** [comment]
I will add a changelog.md later and from then on (1.0.17) we will strictly follow the semver.

I will close this issue when I added the changelog.
